import { formatKES, makeInvoiceNumber } from "./format";

export async function downloadInvoice({ items, total, paymentMethod }) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const invoiceNo = makeInvoiceNumber();
  const dateStr = new Date().toLocaleDateString("en-KE", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const marginX = 48;
  let y = 60;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("NATIVE254", marginX, y);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("IT Solutions & Tech Skills, Nairobi", marginX, y + 16);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("INVOICE", 545, y, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`No. ${invoiceNo}`, 545, y + 16, { align: "right" });
  doc.text(dateStr, 545, y + 30, { align: "right" });

  y += 60;
  doc.setDrawColor(20, 20, 20);
  doc.line(marginX, y, 545, y);
  y += 24;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Description", marginX, y);
  doc.text("Category", 330, y);
  doc.text("Qty", 430, y, { align: "right" });
  doc.text("Amount (KES)", 545, y, { align: "right" });
  y += 8;
  doc.setDrawColor(180, 180, 180);
  doc.line(marginX, y, 545, y);
  y += 20;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  items.forEach((item) => {
    doc.text(item.title, marginX, y, { maxWidth: 260 });
    doc.text(item.category, 330, y);
    doc.text(String(item.qty), 430, y, { align: "right" });
    doc.text(
      Number(item.price * item.qty).toLocaleString("en-KE"),
      545,
      y,
      { align: "right" }
    );
    y += 22;
  });

  y += 6;
  doc.line(marginX, y, 545, y);
  y += 26;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Total due", 400, y, { align: "right" });
  doc.text(formatKES(total), 545, y, { align: "right" });

  y += 34;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Selected payment method: ${paymentMethod}`, marginX, y);
  y += 30;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("To confirm this order:", marginX, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("1. Complete payment using the method above.", marginX, y);
  y += 14;
  doc.text(
    "2. Send your payment confirmation message to 0716 369 996 (WhatsApp)",
    marginX,
    y
  );
  y += 14;
  doc.text("   or email info.native@gmail.com with this invoice number.", marginX, y);
  y += 30;

  doc.setDrawColor(220, 220, 220);
  doc.line(marginX, y, 545, y);
  y += 18;
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "This is a pro-forma invoice generated by Native254 for record and confirmation purposes.",
    marginX,
    y
  );

  doc.save(`Native254-Invoice-${invoiceNo}.pdf`);
  return invoiceNo;
}
